### PR TITLE
Update PULL_REQUEST_TEMPLATE_2.md

### PR DESCRIPTION
**Pull request by tonilopezmr**
Added icons for the rest of the sections in PR TEMPLATE 2. It's very weird to see only the first two icons and the rest of the sections without it.

### CODE REVIEW

**Comment by pedrovgs** [comment]
@Serchinastico I activated Travis for this repository and added a checkstyle for the markdown we've written in these documents. But as the PR is not approved by two karumies I decided to keep it open for some days.

**Comment by pedrovgs** [comment]
Look -> https://github.com/Karumi/project-quality-assurance/pull/5

**Comment by Serchinastico** [comment]
That's great! Sorry I didn't even realize that PR was created at all 😓

**Comment by pedrovgs** [comment]
Thanks @tonilopezmr and @Serchinastico

**Pull request merged**
